import crypto from 'crypto';
import express from 'express';
import { query } from '../db.js';
import { requireAuth } from '../middleware/auth.js';
const router=express.Router();
const DT=()=>process.env.DISCORD_TOKEN||process.env.DISCORD_BOT_TOKEN;
const KEY=crypto.createHash('sha256').update(process.env.JWT_SECRET||'mld').digest();
function enc(v){const iv=crypto.randomBytes(12),c=crypto.createCipheriv('aes-256-gcm',KEY,iv),x=Buffer.concat([c.update(v,'utf8'),c.final()]);return 'enc:'+iv.toString('base64url')+':'+c.getAuthTag().toString('base64url')+':'+x.toString('base64url')}
async function da(path,token=DT()){const r=await fetch('https://discord.com/api/v10'+path,{headers:{Authorization:'Bot '+token}});let d={};try{d=await r.json()}catch{}return {ok:r.ok,d}}
async function adminInGuild(uid,gid){const u=await query('SELECT discord_id FROM users WHERE id=$1',[uid]),did=u.rows[0]?.discord_id;if(!did||!gid||!DT())return false;const m=await da('/guilds/'+gid+'/members/'+did);if(!m.ok)return false;const rr=await da('/guilds/'+gid+'/roles');if(!rr.ok)return false;const ids=new Set(m.d.roles||[]);let p=BigInt((rr.d.find(x=>String(x.id)===String(gid))||{}).permissions||'0');for(const r of rr.d)if(ids.has(String(r.id)))p|=BigInt(r.permissions||'0');return (p&8n)===8n}
async function can(req,gid){return !!req.user?.is_owner||await adminInGuild(req.user.id,gid)}
async function subInfo(botId){const q=await query("SELECT id,started_at,expires_at,active,features FROM bot_subscriptions WHERE bot_id=$1 AND active=true AND expires_at>NOW() ORDER BY expires_at DESC LIMIT 1",[botId]);return q.rows[0]||null}
router.get('/stats',requireAuth,async(req,res)=>{try{const q=req.user.is_owner?await query('SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE active)::int active FROM bots'):await query('SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE active)::int active FROM bots WHERE user_id=$1',[req.user.id]);res.json(q.rows[0]||{total:0,active:0})}catch(e){res.status(500).json({error:'تعذر تحميل إحصائيات البوتات'})}});
router.get('/public',async(req,res)=>{try{const q=await query('SELECT id,name,guild_id,avatar,bot_type,watching,site_url,locked,active,created_at FROM bots ORDER BY created_at DESC');res.json({bots:q.rows})}catch(e){res.status(500).json({error:'تعذر تحميل البوتات'})}});
router.get('/',requireAuth,async(req,res)=>{try{const q=await query(req.user.is_owner?'SELECT * FROM bots':'SELECT * FROM bots WHERE user_id=$1',req.user.is_owner?[]:[req.user.id]);const a=[];for(const x of q.rows)if(req.user.is_owner||await adminInGuild(req.user.id,x.guild_id))a.push(x);res.json({bots:await Promise.all(a.map(async ({token,...x})=>({...x,subscription:await subInfo(x.id)})))})}catch(e){res.status(500).json({error:'تعذر تحميل بوتاتك'})}});
router.post('/check-guild',requireAuth,async(req,res)=>{const gid=String(req.body.guild_id||'').trim();if(!/^\d{17,20}$/.test(gid))return res.status(400).json({error:'ايدي السيرفر غير صحيح'});if(!await can(req,gid))return res.status(403).json({error:'تحتاج صلاحية Administrator في السيرفر'});const g=await da('/guilds/'+gid+'?with_counts=true');if(!g.ok)return res.status(404).json({error:'السيرفر غير موجود أو البوت لا يستطيع الوصول إليه'});res.json({guild:{id:g.d.id,name:g.d.name,icon:g.d.icon?'https://cdn.discordapp.com/icons/'+g.d.id+'/'+g.d.icon+'.png?size=128':null,memberCount:g.d.approximate_member_count||0},isAdmin:true})});
router.post('/',requireAuth,async(req,res)=>{try{const name=String(req.body.name||'').trim(),token=String(req.body.token||'').trim(),gid=String(req.body.guild_id||'').trim(),type=String(req.body.bot_type||'general');if(!name||!token||!gid)return res.status(400).json({error:'أدخل كل الحقول'});if(!await can(req,gid))return res.status(403).json({error:'تحتاج صلاحية Administrator في السيرفر'});const r=await fetch('https://discord.com/api/v10/users/@me',{headers:{Authorization:'Bot '+token}});if(!r.ok)return res.status(400).json({error:'توكن البوت غير صالح'});const info=await r.json();const m=await fetch('https://discord.com/api/v10/guilds/'+gid+'/members/'+info.id,{headers:{Authorization:'Bot '+token}});if(!m.ok)return res.status(400).json({error:'أضف البوت إلى السيرفر أولًا ثم أعد المحاولة'});const invite='https://discord.com/api/oauth2/authorize?client_id='+info.id+'&permissions=8&scope=bot%20applications.commands',avatar=info.avatar?'https://cdn.discordapp.com/avatars/'+info.id+'/'+info.avatar+'.png?size=128':'/logo.svg.JPG';const presets={general:[{name:'hello',description:'ترحيب',response:'ياهلا {user} في {server}!',enabled:true}],welcome:[{name:'help',description:'المساعدة',response:'أنا بوت الترحيب الخاص بالسيرفر.',enabled:true}],moderation:[{name:'rules',description:'القوانين',response:'يرجى الالتزام بقوانين السيرفر واحترام الجميع.',enabled:true}],tickets:[{name:'ticket',description:'التذاكر',response:'للمساعدة افتح تذكرة من موقع ملاذ أو تواصل مع الإدارة.',enabled:true}],games:[{name:'games',description:'رابط الألعاب',response:'🎮 ألعاب ملاذ: https://web-production-3224.up.railway.app/#games',enabled:true}],cinema:[{name:'cinema',description:'مكتبة السينما',response:'🎬 سينما ملاذ: https://web-production-3224.up.railway.app/#cinema',enabled:true}],custom:[{name:'hello',description:'أمر مخصص',response:'ياهلا {user}!',enabled:true}]};const settings={prefix:'!',commands:presets[type]||presets.general};const q=await query('INSERT INTO bots(user_id,name,token,guild_id,avatar,bot_type,invite_url,watching,site_url,locked,active,settings) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,TRUE,TRUE,$10) RETURNING *',[req.user.id,name,enc(token),gid,avatar,type,invite,'MLD | فهد المطيري','https://discord.com/users/w4px',JSON.stringify(settings)]);const {token:_,...b}=q.rows[0];res.json({bot:b})}catch(e){console.error(e);res.status(500).json({error:'تعذر إضافة البوت'})}});
router.get('/:id',requireAuth,async(req,res)=>{const q=await query('SELECT * FROM bots WHERE id=$1',[req.params.id]),b=q.rows[0];if(!b)return res.status(404).json({error:'غير موجود'});if(!req.user.is_owner&&String(b.user_id)!==String(req.user.id)&&!(await adminInGuild(req.user.id,b.guild_id)))return res.status(403).json({error:'ما تملك الصلاحية'});const {token,...safe}=b;res.json({bot:{...safe,subscription:await subInfo(b.id)}})});
router.post('/:id/toggle',requireAuth,async(req,res)=>{const q=await query('SELECT * FROM bots WHERE id=$1',[req.params.id]),b=q.rows[0];if(!b)return res.status(404).json({error:'البوت غير موجود'});if(!req.user.is_owner&&String(b.user_id)!==String(req.user.id)&&!(await adminInGuild(req.user.id,b.guild_id)))return res.status(403).json({error:'تحتاج صلاحية Administrator'});const active=!b.active;await query('UPDATE bots SET active=$1 WHERE id=$2',[active,req.params.id]);res.json({active,message:active?'تم التشغيل':'تم الإيقاف'})});
router.patch('/:id/config',requireAuth,async(req,res)=>{try{const q=await query('SELECT * FROM bots WHERE id=$1',[req.params.id]),b=q.rows[0];if(!b)return res.status(404).json({error:'البوت غير موجود'});if(!req.user.is_owner&&String(b.user_id)!==String(req.user.id)&&!(await adminInGuild(req.user.id,b.guild_id)))return res.status(403).json({error:'ما تملك الصلاحية'});const prefix=String(req.body.prefix||'!').trim().slice(0,4)||'!';const commands=Array.isArray(req.body.commands)?req.body.commands.slice(0,40).map(x=>({name:String(x.name||'').toLowerCase().replace(/[^a-z0-9_-]/g,'').slice(0,32),description:String(x.description||'').slice(0,100),response:String(x.response||'').slice(0,1800),enabled:x.enabled!==false})).filter(x=>x.name&&x.response):[];const settings={...(b.settings||{}),prefix,commands,welcomeChannelId:String(req.body.welcomeChannelId||'').replace(/[^0-9]/g,'').slice(0,24),welcomeMessage:String(req.body.welcomeMessage||'ياهلا {user} في {server}!').slice(0,1000)};const type=String(req.body.bot_type||b.bot_type||'general').slice(0,32);await query('UPDATE bots SET bot_type=$1,settings=$2 WHERE id=$3',[type,JSON.stringify(settings),b.id]);res.json({message:'تم حفظ إعدادات البوت وأوامره؛ تُطبّق تلقائيًا خلال ثوانٍ.',settings,bot_type:type});}catch(e){console.error('bot config',e.message);res.status(500).json({error:'تعذر حفظ إعدادات البوت'});}});
router.get('/:id/config',requireAuth,async(req,res)=>{const q=await query('SELECT id,user_id,guild_id,bot_type,settings,runtime_status,last_seen_at,last_error FROM bots WHERE id=$1',[req.params.id]),b=q.rows[0];if(!b)return res.status(404).json({error:'البوت غير موجود'});if(!req.user.is_owner&&String(b.user_id)!==String(req.user.id)&&!(await adminInGuild(req.user.id,b.guild_id)))return res.status(403).json({error:'ما تملك الصلاحية'});res.set('Cache-Control','private, no-store').json({bot:b});});
router.delete('/:id',requireAuth,async(req,res)=>{const q=await query('SELECT * FROM bots WHERE id=$1',[req.params.id]),b=q.rows[0];if(!b)return res.status(404).json({error:'غير موجود'});if(!req.user.is_owner&&String(b.user_id)!==String(req.user.id)&&!(await adminInGuild(req.user.id,b.guild_id)))return res.status(403).json({error:'ما تملك الصلاحية'});await query('DELETE FROM bots WHERE id=$1',[req.params.id]);res.json({message:'تم الحذف'})});
export default router;